name: Package and release
on:
    push:
        tags:
        - '**'
jobs:
    release:
        runs-on: ubuntu-latest
        env:
            GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - uses: actions/checkout@v2
            - name: Package and release
            uses: BigWigsMods/packager@v2
